#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Cyphondock documentation build configuration file, created by
# sphinx-quickstart on Thu Apr 13 10:02:57 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.txt'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Cyphondock'
copyright = '2017, Leila Hadj-Chikh'
author = 'Leila Hadj-Chikh'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '1.6'
# The full version, including alpha/beta/rc tags.
release = '1.6.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/images/favicon.ico'

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Cyphondock-doc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Cyphondock.tex', 'Cyphondock Documentation',
     'Leila Hadj-Chikh', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'cyphondock', 'Cyphondock Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Cyphondock', 'Cyphondock Documentation',
     author, 'Cyphondock', 'One line description of project.',
     'Miscellaneous'),
]


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'django': ('https://docs.djangoproject.com/en/1.10/',
               'https://docs.djangoproject.com/en/1.10/_objects/'),
    'elasticsearch': ('https://elasticsearch-py.readthedocs.io/en/5.0.1/',
                      None),
    'mongodb': ('http://api.mongodb.com/python/current/', None),
    'psycopg2': ('http://initd.org/psycopg/docs/', None),
    'python': ('https://docs.python.org/3/', None),
    # 'sphinx': ('http://www.sphinx-doc.org/en/stable/', None),
}

rst_epilog = """
.. _Cyphon: https://github.com/dunbarcyber/cyphon
.. _Elasticsearch: https://www.elastic.co/products/elasticsearch/
.. _Django: https://www.djangoproject.com/
.. _Docker: https://www.docker.com/
.. _Filebeat: https://www.elastic.co/products/beats/filebeat/
.. _Kibana: https://www.elastic.co/products/kibana/
.. _Logstash: https://www.elastic.co/products/logstash/
.. _MongoDB: https://www.mongodb.com/
.. _Nginx: https://www.nginx.com/resources/wiki/
.. _PostgreSQL: https://www.postgresql.org/
.. _RabbitMQ: https://www.rabbitmq.com/
.. _docker-compose.yml: https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.yml
.. _docker-compose.dev.yml: https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.dev.yml
.. _docker-compose.override.yml: https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.override.yml
.. _docker-compose.travis.yml: https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.travis.yml
.. _docker-compose.backends.yml: https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.backends.yml
"""

def setup(app):
    app.add_javascript('js/cyphondock.js')
